# Generated by Django 4.2.7 on 2025-12-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='申請番号')),
                ('application_type', models.CharField(choices=[('work', '作業申請'), ('construction', '工事申請'), ('tool_bringin', '工具持込申請'), ('restricted_entry', '制限エリア立入申請'), ('restricted_tool', '制限エリア工具持込申請')], max_length=30, verbose_name='申請種別')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='申請内容詳細')),
                ('company_name', models.CharField(max_length=200, verbose_name='申請企業名')),
                ('work_location', models.CharField(blank=True, max_length=200, verbose_name='作業場所')),
                ('work_start_date', models.DateField(blank=True, null=True, verbose_name='作業開始予定日')),
                ('work_end_date', models.DateField(blank=True, null=True, verbose_name='作業終了予定日')),
                ('worker_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='作業人数')),
                ('tool_list', models.TextField(blank=True, help_text='改行区切りで入力', verbose_name='持込工具リスト')),
                ('restricted_area', models.CharField(blank=True, max_length=200, verbose_name='制限エリア名')),
                ('entry_purpose', models.TextField(blank=True, verbose_name='立入目的')),
                ('entry_members', models.TextField(blank=True, help_text='氏名、所属を改行区切りで入力', verbose_name='立入者リスト')),
                ('contractor_name', models.CharField(blank=True, max_length=200, verbose_name='施工業者名')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '申請中'), ('received', '受付済'), ('approved', '承認済'), ('rejected', '却下'), ('returned', '差し戻し')], default='draft', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='申請日時')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='受付日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '申請',
                'verbose_name_plural': '申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('submit', '申請'), ('receive', '受付'), ('approve', '承認'), ('reject', '却下'), ('return', '差し戻し')], max_length=20, verbose_name='ステップ種別')),
                ('status', models.CharField(choices=[('pending', '未処理'), ('processing', '処理中'), ('completed', '完了'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='workflow.application', verbose_name='申請')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_steps', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
            ],
            options={
                'verbose_name': 'ワークフローステップ',
                'verbose_name_plural': 'ワークフローステップ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendor', '取引先'), ('receiver', '受付担当'), ('approver', '承認者'), ('admin', '管理者')], default='vendor', max_length=20, verbose_name='役割')),
                ('company_name', models.CharField(max_length=200, verbose_name='企業名')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.application', verbose_name='申請')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='コメント者')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workflow/attachments/%Y/%m/%d/', verbose_name='ファイル')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflow.application', verbose_name='申請')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='workflow_ap_status_1a44b7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='workflow_ap_applica_b1bd84_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-created_at'], name='workflow_ap_applica_8ad404_idx'),
        ),
    ]
