# Generated by Django 4.2.7 on 2025-12-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ロール名')),
                ('role_type', models.CharField(choices=[('receiver', '受付'), ('approver', '承認')], max_length=20, verbose_name='ロール種別')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ワークフローロール',
                'verbose_name_plural': 'ワークフローロール',
                'ordering': ['role_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(max_length=30, unique=True, verbose_name='申請種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approver_role', models.ForeignKey(limit_choices_to={'is_active': True, 'role_type': 'approver'}, on_delete=django.db.models.deletion.PROTECT, related_name='approver_for_types', to='workflow.workflowrole', verbose_name='承認ロール')),
                ('receiver_role', models.ForeignKey(limit_choices_to={'is_active': True, 'role_type': 'receiver'}, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_for_types', to='workflow.workflowrole', verbose_name='受付ロール')),
            ],
            options={
                'verbose_name': '申請種別設定',
                'verbose_name_plural': '申請種別設定',
                'ordering': ['application_type'],
            },
        ),
        migrations.CreateModel(
            name='RoleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='割当日時')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='割当者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workflow.workflowrole', verbose_name='ロール')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_roles', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ロールメンバー',
                'verbose_name_plural': 'ロールメンバー',
                'ordering': ['role', 'assigned_at'],
                'unique_together': {('role', 'user')},
            },
        ),
    ]
